model:
  attention_dropout: 0.0
  family: bert_padded
  hidden_dropout: 0.0
  mlp: []
  n_embd: 128
  n_head: 2
  n_layer: 3
  n_positions: 64
  tokenizer: learnable
  use_layer_norm: null
model_type: transformer
out_dir: models/transformer-plotting_type=mu-family=bert_padded-n_positions=64-pretraining_sigma_tasks=1-pretraining_mu_tasks=16-family=bert_padded-hid_dim=128-layer=3-head=2-tokenizer=learnable
training:
  batch_size: 4
  curriculum:
    dims:
      end: 1
      inc: 0
      interval: 100001
      start: 1
    points:
      end: 1024
      inc: 64
      interval: 10000
      start: 64
  data_kwargs: null
  learning_rate: 0.0001
  loss: normalized_mean_squared_error
  plotting_type: mu
  pretraining_mu_tasks: 16
  pretraining_sigma_tasks: 1
  save_every_steps: 500000
  save_plot_every_steps: 1000
  train_steps: 500001
wandb:
  entity: chsanford4
  log_every_steps: 50
  name: normal_means
  project: in-context-model-selection
